
version: '3.1'
services:

  PFLB_task1:
    image: ubuntu:latest
    container_name: PFLB1
    hostname: PFLB
    command: bash -c "cd PFLB && touch change_me.txt"
    ports:
      - 81:81
    volumes:
      - .:/PFLB

  PFLB_task2:
    image: ubuntu:latest
    container_name: PFLB2
    hostname: PFLB
    command: bash -c "cd PFLB && chmod +x change_me.txt"
    ports:
      - 82:82
    volumes:
      - .:/PFLB

